trigger: none

pool: devops-agents

steps:
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
    backendServiceArm: 'devops-connect'
    backendAzureRmStorageAccountName: 'abhistgpipe'
    backendAzureRmContainerName: 'abhicontainer'
    backendAzureRmKey: 'abhipipe.tfstate'
- task: tfsec@1
  inputs:
    version: 'v1.26.0'
    dir: '(System.DefaultWorkingDirectory)/environments/dev'